-- Cue/loudness analysis results (from autocue-rs) attached to songs.

ALTER TABLE songs ADD COLUMN IF NOT EXISTS cue_in DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS cue_out DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS cross_start_next DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS loudness REAL;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS loudness_range REAL;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS true_peak REAL;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS true_peak_db REAL;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS amplify REAL;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS sustained_ending BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS longtail BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS analyzed_at TIMESTAMPTZ;
